name: Dastle Blog
markdown: kramdown
permalink: /:year/:month/:day/:title
timezone: Asia/Shanghai
livereload: true
baseurl: https://blog.dastle.net
author: David Z
gems: [jekyll-paginate]
plugins: [jekyll-paginate]
paginate: 7
paginate_path: "/page:num/"
